#ifndef __SYSC_H__
#define __SYSC_H__

#include <common.h>
#include "./def.h"

#ifndef FIN
#define FIN     (24000000)
#endif

typedef enum 
{
  // CLK_DIV0
  eCLKDIV_PCLKPSYS, 
  eCLKDIV_HCLKPSYS, 
  eCLKDIV_PCLKDSYS, 
  eCLKDIV_HCLKDSYS, 
  eCLKDIV_PCLKMSYS, 
  eCLKDIV_HCLKMSYS,
  eCLKDIV_A2M, 
  eCLKDIV_APLL,
  // CLK_DIV1
  eCLKDIV_CSIS, 
  eCLKDIV_FIMD, 
  eCLKDIV_CAM1, 
  eCLKDIV_CAM0, 
  eCLKDIV_FIMC, 
  eCLKDIV_TBLK,
  // CLK_DIV2
  eCLKDIV_MFC, 
  eCLKDIV_G3D,
  // CLK_DIV3
  eCLKDIV_FIMC2, 
  eCLKDIV_FIMC1, 
  eCLKDIV_FIMC0, 
  eCLKDIV_MDNIEPWM, 
  eCLKDIV_MDNIE, 
  // CLK_DIV4
  eCLKDIV_UART3, 
  eCLKDIV_UART2, 
  eCLKDIV_UART1, 
  eCLKDIV_UART0, 
  eCLKDIV_MMC3, 
  eCLKDIV_MMC2, 
  eCLKDIV_MMC1, 
  eCLKDIV_MMC0,
  // CLK_DIV5
  eCLKDIV_PWM, 
  eCLKDIV_SPI2, 
  eCLKDIV_SPI1, 
  eCLKDIV_SPI0,
  // CLK_DIV6
  eCLKDIV_ONEDRAM, 
  eCLKDIV_PWI, 
  eCLKDIV_HPM, 
  eCLKDIV_COPY, 
  eCLKDIV_ONENAND, 
  eCLKDIV_AUDIO2, 
  eCLKDIV_AUDIO1, 
  eCLKDIV_AUDIO0, 
  // CLK_DIV7
  eCLKDIV_DPM, 
  eCLKDIV_DVSEM
}CLKDIV_ID;


u32 SYSC_GetClkDiv(CLKDIV_ID eId);

#endif
